MONGODB_HOST: mongodb-{{ env }}.maxdevopstech.online
REDIS_HOST: redis-{{ env }}.maxdevopstech.online
MYSQL_HOST: mysql-{{ env }}.maxdevopstech.online 
RABBITMQ_HOST: rabbitmq-{{ env }}.maxdevopstech.online 
CATALOGUE_HOST: catalogue-{{ env }}.maxdevopstech.online
USER_HOST: user-{{ env }}.maxdevopstech.online
CART_HOST: cart-{{ env }}.maxdevopstech.online
SHIPPING_HOST: shipping-{{ env }}.maxdevopstech.online
PAYMENT_HOST: payment-{{ env }}.maxdevopstech.online